name: build-and-deploy

on:
  push:
    branches:
      - master   # ajusta según tu rama principal

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    environment: ixxitecnologia   # nombre de tu Environment en GitHub

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up PHP 8.3
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.3'

      - name: Install Composer dependencies
        run: composer install --no-dev --optimize-autoloader

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install NPM dependencies
        run: npm ci

      - name: Build frontend assets
        run: npm run build

      - name: Deploy via SFTP
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.IONOS_HOST }}
          username: ${{ secrets.IONOS_USER }}
          password: ${{ secrets.IONOS_PASSWORD }}
          port: 22
          source: "./"
          target: "htdocs"

